[project]
name = "cicd-template"
version = "0.1.0"
description = "A template for CI/CD development tools."
authors = [{ name = "nicklamiller", email = "nicklamiller@gmail.com" }]
requires-python = "==3.13.*"
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools.packages.find]
include = ["cicd_template"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true

[tool.ruff.lint]
select = [
    "E", # pycodestyle - Error
    "I", # isort
    "F", # Pyflakes
    "PT", # flake8-pytest-style
]
