name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  unit-tests:
    name: Unit tests
    uses: ./.github/workflows/unit-tests.yml

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
