name: Unit Tests

on:
  workflow_call:

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: true
          environments: test
          locked: true
          pixi-version: v0.62.2

      - name: Run tests
        run: |
          pixi run pytest \
            --color=yes \
            --durations=0 \
            --durations-min=1
